- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
Fixes an issue where forcing a non-null expression. From my understanding, this check tells Typescript we know the results will be present and not empty. That guarantee seems to be broken after updating dependencies. This PR aims to resolve the issue at hand and get things back to 🟢 .
```
Array.prototype.map called on null or undefined
```
Checklist:
> fix: remove forcing non-null expression

- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.ts
- plugins/announcements-backend/src/search/api.ts
- plugins/announcements/package.json
- plugins/announcements/src/setupTests.ts
- yarn.lock
Summary:
We should use the provided APIs from Backstage
Details:
The backend is currently using `crossFetch`. Backstage provides a fetch API that wraps this with additional backstage-centric features. 
Checklist:
> refactor: use backstage fetch api

- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/CategoriesDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/persistenceContext.test.ts
- yarn.lock
The CatagoriesDatabase and persistenceContext are now reporting 100% test coverage. There is more work to be done for the AnnouncementsDatabase, but this PR includes a test to get us started.
Checklist:
> test: initial tests for persistence (context, announcements, categories)

- package.json
- plugins/announcements/package.json
- yarn.lock
Drops support for node16, updates to support node18 and node20.
Checklist:
> chore: drop node16 support

- CONTRIBUTING.md
The link to the license in the contributing guide is incorrect
Checklist:
> fix: broken link to license

- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
- plugins/announcements/src/api.ts
Adds unit tests for AnnouncementDatabase. This brings the persistence package to 100% test coverage. 
Checklist:
> test: AnnouncementDatabase

- plugins/announcements-backend/src/service/router.test.ts
- plugins/announcements-backend/src/service/utils.test.ts
Add unit tests for existing routes.
**Announcements**
- /GET
- /POST 
- /PUT
**Categories**
- /GET
- /POST
Checklist:
> test: announcements backend routes

- plugins/announcements-backend/src/service/standaloneServer.ts
SingleHostDiscovery is deprecated.
Checklist:
> refactor: replace SingleHostDiscovery with HostDiscovery

- .github/ISSUE_TEMPLATE/bug.yaml
Use the existing bug issue template from `backstage/backstage`
Checklist:
> fix: bug.yaml

- .changeset/spicy-glasses-listen.md
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.test.ts
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.ts
- plugins/announcements-backend/src/search/api.test.ts
- plugins/announcements-backend/src/search/api.ts
The `fetchApi` provided by Backstage is intended to be used in the front-end. This PR updates the collator to use native fetch instead.
Checklist:
> fix: use fetch in AnnouncementCollatorFactory

- package.json
- plugins/announcements/package.json
- yarn.lock
The create-app command provided by Backstage creates new instances that do not support node16. This PR moves away from node 16 and supports 18 and 20.
Checklist:
> feat: support node 18 and 20

- .changeset/fifty-olives-run.md
- plugins/announcements-backend/src/search/api.ts
On the scheduled collector task for the search feature, it tries to fetch announcements on `GET /api/announcements/` , which makes search entries empty.
To be taken into account when https://github.com/procore-oss/backstage-plugin-announcements/issues/23 is started 😄 
Observed logs on our Backstage instance:
```
12:57:48.461Z[22m [34mbackstage[39m [32minfo[39m ::ffff:127.0.0.1 - - [24/Oct/2023:12:57:48 +0000] "GET /api/announcements/ HTTP/1.1" 401 12 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" [36mtype[39m=incomingRequest
[1] [2m2023-10-24T12:57:48.474Z[22m [34msearch[39m [31merror[39m Collating documents for announcements failed: ResponseError: Request failed with 401 Error [36mtype[39m=plugin [36mdocumentType[39m=announcements
[1] [2m2023-10-24T12:57:48.474Z[22m …
```
> fix: use correct api path on collector

- .changeset/pink-lamps-sit.md
- plugins/announcements-backend/src/service/router.ts
Making these changes based on the recommendation from [Backstage maintainer](https://github.com/K-Phoen/backstage-plugin-announcements/pull/153).
Code was taken 1:1 from the linked pull request. 
> We (the permission framework maintainers) updated the correct usage of createPermissionIntegrationRouter, but the docs remained outdated. As part of fixing the docs (https://github.com/backstage/backstage/pull/17388) we're making PRs to help fix the issue in community plugins as well.
Checklist:
> Add missing createPermissionIntegrationRouter call

- .changeset/sixty-forks-divide.md
- plugins/announcements-backend/src/search/api.ts
This time I tested it on my instance. Collector successfully fetched announcements.
```txt
[1] 2023-10-27T09:22:37.744Z search info Collating documents for announcements via AnnouncementCollatorFactory type=plugin documentType=announcements
[1] 2023-10-27T09:22:37.745Z search info indexing announcements type=plugin
[1] 2023-10-27T09:22:37.767Z backstage info ::ffff:127.0.0.1 - - [27/Oct/2023:09:22:37 +0000] "GET /api/announcements/announcements HTTP/1.1" 200 205 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2023-10-27T09:22:37.770Z search debug got 1 announcements type=plugin
[1] 2023-10-27T09:22:37.770Z search debug mapping announcement 8541a1dc-2725-4c79-a367-dc91bd43282b to indexable document type=plugin
[1] 2023-10-27T09:22:37.779Z search info …
```
> fix: AnnouncementCollatorApi iterable error

- .changeset/shaggy-fans-glow.md
- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.test.ts
- plugins/announcements-backend/src/search/api.test.ts
- plugins/announcements-backend/src/service/announcementsContextBuilder.test.ts
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.ts
- plugins/announcements-backend/src/service/persistence/CategoriesDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/persistenceContext.test.ts
- yarn.lock
This PR adds unit tests for the **announcements-backend** plugin. There is an open [issue](https://github.com/procore-oss/backstage-plugin-announcements/issues/20) requesting help with unit testing the frontend. 
The router is partially tested. There are no other unit tests at this time.
**General overview of progress**
**Database**
**Search**
**Persistence context & service router**
> test: unit test announcements-backend

- .changeset/mean-plants-wait.md
- plugins/announcements-backend/package.json
"Since this change[ [insert hyperlink](https://github.com/procore-oss/backstage-plugin-announcements/commit/4968543f32f180475ce9c3a6be6cd3b00512d5f0)], the migrations folder isn't correct for the build.
This change fixes this error during Backstage startup:
```log
[1] Backend failed to start up [Error: ENOENT: no such file or directory, scandir '/home/io/workspace/elca-backstage/node_modules/@procore-oss/backstage-plugin-announcements-backend/db/migrations']
```
> fix: set correct database migrations folder path

- .changeset/sour-coins-give.md
- docs/index.md
- plugins/announcements/dev/index.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.test.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/Router.tsx
Solves https://github.com/procore-oss/backstage-plugin-announcements/issues/117
Allow the user to override the title length in an AnnouncementCard
Seeded data with the default length -> no change to end user
`<AnnouncementsPage />`
`<AnnouncementsPage cardOptions={{ titleLength: 1 }} />`
`<AnnouncementsPage cardOptions={{ titleLength: 5 }} />`
We officially have some unit tests for the frontend 🎉 
**Before** 
**After**
Checklist:
> feat: allow overriding length of announcement title

- .changeset/stale-vans-glow.md
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.test.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
Checklist:
Details:
- truncated title now includes ellipsis
- hovering over title will display toolip with the full title
> feat: truncated card titles includes ellipsis and tooltip with full title

- .changeset/six-trainers-hope.md
- plugins/announcements/src/index.ts
Details:
Export the `announcementsApiRef`. Users need this to implement tests on their end. 
Checklist:
> fix: export announcementsApiRef

- plugins/announcements-backend/src/service/standaloneServer.ts
`SingleHostDiscovery` is deprecated in favor of `HostDiscovery`.
Checklist:
> chore: replace SingleHostDiscovery with HostDiscovery

- .changeset/new-bikes-admire.md
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
Checklist:
This PR implement this: https://github.com/procore-oss/backstage-plugin-announcements/issues/126
Default component already supports displaying `userEntity` on hover. Let's see if it still makes sense to use the `<Link>` component.
> Use EntityDisplayName

- .github/workflows/ci.yaml
> chore: be explicit on ci github action is read-only

- .changeset/happy-numbers-clean.md
- package.json
- plugins/announcements/package.json
- yarn.lock
We missed upgrading to React 18 while upgrading backstage to 1.22.1. This PR gets us aligned with `backstage/backstage`.
Checklist:
> feat: support for React18

- .changeset/good-taxis-smile.md
- plugins/announcements-backend/src/index.ts
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.ts
I'll chalk this up as a learning opportunity with the new backend architecture for Backstage. A backend module ends with having a single export, the module itself, so the deprecation telling the end user to migrate is incorrect. 
The search module for announcements does not export the collator. You should only migrate if leveraging the new backend system.
Checklist:
> fix: add exporting collator back to @procore-oss/backstage-plugin-announcements-backend

- .changeset/tame-kids-thank.md
- plugins/announcements/src/components/AnnouncementPage/AnnouncementPage.tsx
Checklist:
I miss this part (https://github.com/procore-oss/backstage-plugin-announcements/pull/160) when we replaced userEntity by DisplayName
> Add missing display name

- plugins/announcements-react/.eslintrc.js
- plugins/announcements-react/README.md
- plugins/announcements-react/package.json
- plugins/announcements-react/src/apis/AnnouncementsApi.ts
- plugins/announcements-react/src/apis/index.ts
- plugins/announcements-react/src/apis/types.ts
- plugins/announcements-react/src/index.ts
- plugins/announcements-react/src/setupTests.ts
- yarn.lock
Taking us another step in the direction of the new architecture.
This package duplicates exporting the `announcementsApiRef` and `AnnouncementsApi` interface. Follow-up PRs will include deprecating and replacing this in the backend.
Checklist:
> feat: new react plugin to provide announcements api refs and interface

- .changeset/lazy-seas-wait.md
- plugins/announcements-react/README.md
- plugins/announcements-react/package.json
- yarn.lock
because it does not follow the proper naming convention
Checklist:
> fix: package name - release @procore-oss/backstage-plugin-announcements-react

- .changeset/honest-bags-visit.md
- plugins/announcements-backend/package.json
- plugins/announcements/package.json
- plugins/announcements/src/api.ts
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementPage/AnnouncementPage.tsx
- plugins/announcements/src/components/AnnouncementsCard/AnnouncementsCard.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.test.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/CategoriesPage/CategoriesPage.tsx
- plugins/announcements/src/components/CreateAnnouncementPage/CreateAnnouncementPage.tsx
- plugins/announcements/src/components/EditAnnouncementPage/EditAnnouncementPage.tsx
- plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx
- plugins/announcements/src/components/NewCategoryDialog/NewCategoryDialog.tsx
- plugins/announcements/src/index.ts
- plugins/announcements/src/plugin.ts
- yarn.lock
Details:
1. Use the new `react` plugin imports where possible
2. Re-export these imports and mark deprecated for backwards compatibility. 
Checklist:
> refactor: use new -react plugin exports

- .changeset/empty-buckets-repair.md
- plugins/announcements-backend/src/api/api.ts
- plugins/announcements-backend/src/api/index.ts
- plugins/announcements-backend/src/index.ts
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.ts
- plugins/announcements-backend/src/service/model.ts
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.ts
- plugins/announcements-backend/src/service/persistence/CategoriesDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/CategoriesDatabase.ts
- plugins/announcements-backend/src/service/router.test.ts
- plugins/announcements-common/src/index.ts
- plugins/announcements-common/src/types.ts
- plugins/announcements-react/package.json
- plugins/announcements-react/src/apis/AnnouncementsApi.ts
- plugins/announcements-react/src/apis/types.ts
- plugins/announcements/src/api.ts
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementPage/AnnouncementPage.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/AnnouncementsPage/useDeleteAnnouncementDialogState.tsx
- plugins/announcements/src/components/CategoriesPage/CategoriesPage.tsx
- plugins/announcements/src/components/CreateAnnouncementPage/CreateAnnouncementPage.tsx
- plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx
- plugins/search-backend-module-announcements/package.json
- plugins/search-backend-module-announcements/src/collators/AnnouncementCollatorFactory.ts
- yarn.lock
There are many areas where types are duplicated. Migrating them to a common package follows the Backstage architecture and reduces duplication.
Checklist:
> refactor: move reusable types to common package

- .github/workflows/release.yaml
`yarn release` fails because it executes `yarn changset publish` which does not work with `yarn workspaces`. This PR updates our release workflow to use the yarn workspace publish commands rather than changesets.
Pending issue: https://github.com/changesets/changesets/pull/674
Backstage is doing similar [here](https://github.com/backstage/backstage/blob/7882ea60d3a82ce9247931822031d795dc6e0e20/.github/workflows/deploy_packages.yml#L180).
Checklist:
> fix: release yarn workspaces properly

- .changeset/shy-moose-flow.md
- docs/index.md
- plugins/announcements/src/components/Router.tsx
Adds a router prop that will allow us to filter on categories.  
#294 
Checklist:
> Adding RouterProps that would allow for filtering by category

- .github/workflows/release.yaml
> fix: changeset should push tags after publish

- .github/workflows/release.yaml
> fix: separate yarn commands in release workflow

- .github/workflows/release.yaml
Attempting to publish each package and ensure releases are updated in GitHub.
Checklist:
> fix: separate commands into two steps

- .changeset/fifty-dodos-knock.md
- docs/index.md
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.test.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
This addresses #298 
Checklist:
> Adding the ability to adjust the button on AnnouncementsPage using props

- .github/workflows/release.yaml
Correct the name for the publishing git tags step.
> chore: rename copy/pasted job name

- .github/workflows/release.yaml
Yarn is not authing correctly to publish packages. Merging this _may_ fix things.
> ci: yarn command is not authenticating properly

- .changeset/big-poems-marry.md
- plugins/announcements/src/components/Router.tsx
This should resolve the issue I was seeing with the values not being available in the latest version.  
Relates to #299 
Checklist:
> Added buttonOptions to router props so that this can be overridden

- .changeset/sour-turkeys-wonder.md
- plugins/announcements/src/components/AnnouncementsCard/AnnouncementsCard.tsx
This allows you to override the default value `gridItem`, which is useful when using the card on a homepage for example. (otherwise it adds a margin to the bottom of the card, making the card inconsistent in size compared to the others)
Checklist:
> Added property variant to AnnouncementsCard

- .changeset/funny-bugs-clean.md
- plugins/announcements-react/README.md
- plugins/announcements-react/package.json
- plugins/announcements-react/src/hooks/index.ts
- plugins/announcements-react/src/hooks/useAnnouncements.ts
- plugins/announcements-react/src/hooks/useCategories.ts
- plugins/announcements-react/src/index.ts
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementsCard/AnnouncementsCard.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/AnnouncementsTimeline/AnnouncementsTimeline.tsx
- plugins/announcements/src/components/CategoriesPage/CategoriesPage.tsx
- plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx
- yarn.lock
I continued to notice a need for having hooks when working on https://github.com/procore-oss/backstage-plugin-announcements/pull/326.
This PR adds two new hooks and reactors to the front end where applicable. While primarily used to refactor existing code, adopters could elect to use these hooks to retrieve and display announcements as they see fit. 
Checklist:
> feat: useAnnouncements and useCategories hooks

- .changeset/funny-bugs-clean.md
- .changeset/silly-owls-sneeze.md
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementForm/CategoryInput.test.tsx
- plugins/announcements/src/components/AnnouncementForm/CategoryInput.tsx
- plugins/announcements/src/components/CreateAnnouncementPage/CreateAnnouncementPage.tsx
- plugins/announcements/src/components/EditAnnouncementPage/EditAnnouncementPage.tsx
Closes https://github.com/procore-oss/backstage-plugin-announcements/issues/314
https://github.com/procore-oss/backstage-plugin-announcements/assets/14222009/a04a4237-f6a1-40b3-911f-f86601a3e88f
Checklist:
> feat: dynamically create category from new announcement form

- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- leave major dependency updates to their own PR so they stand out and are tested correctly
- prefix the PRs with `chore(deps)` to adhere to conventional commits
- Why?
- To prevent supply chain attack. Tags can move. They are mutable. SHAs are not.
- used [frizbee](https://github.com/stacklok/frizbee)
- ran `frizbee ghactions -d .github/workflows` locally
- also fixes formatting
Checklist:
> chore: group dependabot updates when minor/patch

- .changeset/late-bags-fly.md
- .changeset/red-hats-notice.md
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.ts
Bug Report: Announcement category cannot be deleted in certain scenarios #385
Signed-off-by: elavsai lavanya.sainik@ericsson.com
Checklist:
> Bug Report: Announcement category cannot be deleted in certain scenarios

- docs/setup.md
When following the setup instructions, the following error occurs:
```
Usage Error: The --cwd option is ambiguous when used anywhere else than the very first parameter provided in the command line, before even the command path
```
Checklist:
> docs(setup): Usage Error: The --cwd option is ambiguous

- .github/workflows/release.yaml
- package.json
`yarn version` is a yarn4 command, and is now colliding with our package.json script name that generates the changset PR. 
This PR updates the name of the script to `version-packages` to prevent a collision.
Checklist:
> fix: yarn version script name collision

- .changeset/strong-balloons-visit.md
- plugins/announcements/src/plugin.ts
The `<AnnouncementsAdminPortal />` should now be exported and available to use.
> fix: export announcements admin portal

- .changeset/clever-rings-protect.md
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.ts
Fixes an issue where the count returned when applying a filter such as `max` is incorrect.
The count is currently not taking into account the number of announcements being filtered out.
> fix: returning incorrect count of announcements when apply filters

- .changeset/strange-pants-own.md
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.test.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/AnnouncementsPage/ContextMenu.tsx
- plugins/announcements/src/components/Router.tsx
Users can now pass in `hideContextMenu` set to true to remove the context menu from the Announcements Page.
**Visibile (default)**
**Hidden**
> Add the ability to optionally hide the context menu

- .changeset/flat-dancers-kneel.md
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.ts
This fixes #495 and effectively reverts #464 which is incorrect.
The UI uses the `count` field to build the navigation between pages, to know how many pages exist, and allow traversing them. #464 broke this, by returning `count` as the number returned entries (an unnecessary value really - `.length` would suffice for that).
The PR also updates and fixes the tests to reflect this.
The DB logic was slightly refactored to be easier to understand, by having two filter functions (`filterState()` and `filterRange()`), both being used by the main result query, but only the first being used for the count query. This results in a proper `count` value.
The changeset for #464 says:
> For example, if there are 2 total announcements in the database, and you request a `max` of 1 announcement, the count …
> Return the proper full count from DB queries

- .changeset/cyan-kiwis-prove.md
- plugins/announcements-backend/README.md
- plugins/announcements-backend/src/index.ts
- plugins/announcements-common/README.md
- plugins/announcements-common/src/index.ts
- plugins/announcements-node/README.md
- plugins/announcements-node/src/index.ts
- plugins/announcements-react/README.md
- plugins/announcements-react/src/index.ts
- plugins/announcements/README.md
- plugins/announcements/src/index.ts
- plugins/search-backend-module-announcements/README.md
- plugins/search-backend-module-announcements/src/index.ts
All plugins have been deprecated and will no longer be maintained within the `@procore-oss` org. Leveraging the community repo offers the ability to have more maintainers, easier contributions, and more features such as taking advantage of the community release process, api reports, and more.
This release adds deprecation warnings to each export, along with a notice at the top of the README. Users should migrate to the associated package under the `@backstage-community` namespace.
The pull request triggering the first release can be found [here](https://github.com/backstage/community-plugins/commit/dae0126bf7356c19c9bd696020a35b900babbfd8).
The announcements plugin has been migrated to the @backstage-community namespace. This will be the last release under the @procore-oss namespace and …
> NOTICE: The announcements plugins have been migrated to backstage/community-plugins
