procore-oss/backstage-plugin-announcements

- plugins/announcements-backend/src/service/utils.test.ts
Copies over the existing test for timestampToDateTime from `backstage/backstage`.
Checklist:
> test: timestampToDateTime

- plugins/announcements-backend/src/service/announcementsContextBuilder.test.ts
> test: context builder

- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/search/api.test.ts
- yarn.lock
100% test coverage for the announcements client used in the search collator. 
Checklist:
> test: AnnouncementsClient

- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.test.ts
- plugins/announcements-backend/src/search/api.test.ts
- yarn.lock
100% test coverage for the collator factory. This is responsible for creating the indexed search results for announcements. 
Really thankful to have come across the following documentation and code examples to help with this
- Backstage search [docs](https://backstage.io/docs/features/search/)
- NewlineDelimitedJsonCollatorFactory.test.ts [[ref](https://github.com/backstage/backstage/blob/e0b5cd9fdba98c9559bd0e98a68276b527dbb1ae/plugins/search-backend-node/src/collators/NewlineDelimitedJsonCollatorFactory.test.ts#L4)]
- ToolDocumentCollatorFactory.test.ts [[ref](https://github.com/backstage/backstage/blob/e0b5cd9fdba98c9559bd0e98a68276b527dbb1ae/plugins/search-backend-module-explore/src/collators/ToolDocumentCollatorFactory.test.ts)]
Checklist:
> test: AnnouncementCollatorFactory

- plugins/announcements/dev/index.tsx
- plugins/announcements/src/components/Admin/AdminPageLayout/AdminPageLayout.tsx
- plugins/announcements/src/components/Admin/AdminPageLayout/index.ts
- plugins/announcements/src/components/Admin/index.ts
- plugins/announcements/src/components/AnnouncementList/AnnouncementList.tsx
- plugins/announcements/src/components/AnnouncementList/index.ts
- plugins/announcements/src/components/Announcements/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/Announcements/ViewAnnouncementContent/ViewAnnouncementContent.tsx
- plugins/announcements/src/components/Announcements/ViewAnnouncementContent/index.ts
- plugins/announcements/src/components/Newsfeed/Newsfeed.tsx
> feat: new admin view

- .gitignore
- docs/setup.md
Details:
The instructions include commands that require you to change directories. This update removes the need for that. 
* updates `.gitignore` to include `.tgz` files. 
* updates the install commands to use `yarn add --cwd`
Checklist:
> docs(readme): update yarn install command

- .changeset/ninety-ravens-turn.md
Changesets were not included in the last two PRs. 😞 
Checklist:
> feat: release versions of original plugins

- .changeset/silent-forks-scream.md
- package.json
- plugins/announcements-backend/package.json
- plugins/announcements/package.json
- yarn.lock
Bumps a significant amount of dev dependencies across all plugins. 
Checklist:
> chore(dev-deps): bump all dev dependencies where possible (comfortable doing so)

- .changeset/sweet-cooks-sip.md
Fixes an error in the previous changeset.
Checklist:
> fix: Update sweet-cooks-sip.md

- plugins/announcements/src/api.ts
Removes a duplicate import statement.
Checklist:
> chore: remove duplicate import

- docs/search.md
- plugins/announcements-backend/src/search/AnnouncementCollatorFactory.ts
- plugins/search-backend-module-announcements/CHANGELOG.md
- plugins/search-backend-module-announcements/README.md
- plugins/search-backend-module-announcements/package.json
- yarn.lock
> Use the correct package name convention

- plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts
> remove skip from db tests

- .changeset/happy-snakes-kiss.md
> fix: published packages did not have yarn workspace replaced before publishing

- .changeset/lucky-trainers-retire.md
- plugins/announcements-common/src/types.ts
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
> Fix paging not working on AnnouncementsPage

- .changeset/red-hats-notice.md
- plugins/announcements-backend/src/service/router.ts
- plugins/announcements-react/src/apis/AnnouncementsApi.ts
- plugins/announcements/src/api.ts
- plugins/announcements/src/components/CategoriesPage/CategoriesPage.tsx
- plugins/announcements/src/components/CategoriesPage/DeleteCategoryDialog.tsx
- plugins/announcements/src/components/CategoriesPage/useDeleteCategoryDialogState.tsx
Checklist:
Signed-off-by: elavsai lavanya.sainik@ericsson.com
> Able to delete announcement category

- .changeset/mighty-lemons-wonder.md
- .changeset/sweet-boxes-provide.md
- docs/setup.md
- package.json
- plugins/announcements-backend/package.json
- plugins/announcements-common/package.json
- plugins/announcements-node/package.json
- plugins/announcements-react/package.json
- plugins/announcements/package.json
- plugins/announcements/src/alpha.ts
- plugins/announcements/src/alpha/apis.ts
- plugins/announcements/src/alpha/entityCards.test.tsx
- plugins/announcements/src/alpha/entityCards.tsx
- plugins/announcements/src/alpha/index.ts
- plugins/announcements/src/alpha/navItems.tsx
- plugins/announcements/src/alpha/pages.tsx
- plugins/search-backend-module-announcements/package.json
- yarn.lock
This PR adds support for [Backstage's new frontend system](https://backstage.io/docs/frontend-system/). This change is backwards compatible and has no affect on consumers who are still using the standard frontend system.
Spotify will be updating OSS plugins to the new frontend & backend as we work towards an updated Backstage plugin framework. We're prioritizing some community favorites first, and the Spotify team will help manage any unintentional issues that arise.
> Add support for Backstage's new frontend system

- .changeset/quiet-goats-cross.md
- README.md
- docs/events.md
- docs/index.md
- plugins/announcements-backend/dev/index.ts
- plugins/announcements-backend/package.json
- plugins/announcements-backend/src/plugin.ts
- plugins/announcements-backend/src/service/router.ts
- plugins/announcements-common/src/constants.ts
- plugins/announcements-common/src/index.ts
- yarn.lock
Adds support for the Backstage event system, along with opening the door to implementing signals. See [events.md](https://github.com/procore-oss/backstage-plugin-announcements/pull/437/files#diff-e070a13a5415feaf83554427f172fb145dcb7c57e396319bcc967c496a3a43f8) for documentation on what's included.
Checklist:
> feat: add support for backstage events system

- .github/workflows/release.yaml
> fix: publish step after updating to yarn4

- .github/workflows/release.yaml
> fix: remove duplicate run statement

- .github/pull_request_template.md
Update to use a pull request template similar to the format you see here.
N/A
> add dedicated pr template

- app-config.yaml
Updates var names to match whats in the sample env
> fix(app-config): postgres env vars were incorrect

- .changeset/three-sloths-argue.md
- plugins/announcements-react/src/hooks/index.ts
- plugins/announcements-react/src/hooks/useAnnouncementsTranslation.ts
- plugins/announcements-react/src/translation.ts
- plugins/announcements/src/components/Admin/AdminPortal/AdminPortal.tsx
- plugins/announcements/src/components/Admin/AnnouncementsContent/AnnouncementsContent.tsx
- plugins/announcements/src/components/Admin/CategoriesContent/CategoriesContent.tsx
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementForm/CategoryInput.tsx
- plugins/announcements/src/components/AnnouncementSearchResultListItem/AnnouncementSearchResultListItem.tsx
- plugins/announcements/src/components/AnnouncementsCard/AnnouncementsCard.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/AnnouncementsPage/ContextMenu.tsx
- plugins/announcements/src/components/AnnouncementsPage/DeleteAnnouncementDialog.tsx
- plugins/announcements/src/components/AnnouncementsTimeline/AnnouncementsTimeline.tsx
- plugins/announcements/src/components/CategoriesForm/CategoriesForm.tsx
- plugins/announcements/src/components/CategoriesPage/CategoriesPage.tsx
- plugins/announcements/src/components/CreateAnnouncementPage/CreateAnnouncementPage.tsx
- plugins/announcements/src/components/EditAnnouncementPage/EditAnnouncementPage.tsx
- plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx
- plugins/announcements/src/components/NewCategoryDialog/NewCategoryDialog.tsx
Adds support for internationalization
Implements internationalization following [Backstage's guidelines](https://backstage.io/docs/plugins/internationalization/)
Closes #491
> feat(Internationalization): adds support for internationalization

- .changeset/flat-islands-travel.md
- plugins/announcements/src/components/AnnouncementForm/AnnouncementForm.tsx
- plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx
- plugins/announcements/src/components/CategoriesForm/CategoriesForm.tsx
- plugins/announcements/src/components/NewAnnouncementBanner/NewAnnouncementBanner.tsx
Added fallback when accessing theme.
Added fallback when accessing theme to solve bug reported in https://github.com/procore-oss/backstage-plugin-announcements/issues/492
nothing
> added: theme access fallbacks
